### ISSUE TITLE
Définir les paramètres pertinents pour le calcul des similarités

### ISSUE THREAD

**Issue by FnyMrc** [GodZer/PFE-ARGOS#14]

**Comment by GodZer** [comment]
# Cloudtrails logs d'EKS

## Cloudtrail log pour l'action _CreateCluster_

```json
{
  "eventVersion": "1.05",
  "userIdentity": {
    "type": "IAMUser",
    "principalId": "AKIAIOSFODNN7EXAMPLE",
    "arn": "arn:aws:iam::<your-account-id>:user/username",
    "accountId": "<your-account-id>",
    "accessKeyId": "AKIAIOSFODNN7EXAMPLE",
    "userName": "username"
  },
  "eventTime": "2018-05-28T19:16:43Z",
  "eventSource": "eks.amazonaws.com",
  "eventName": "CreateCluster",
  "awsRegion": "<region-code>",
  "sourceIPAddress": "205.251.233.178",
  "userAgent": "PostmanRuntime/6.4.0",
  "requestParameters": {
    "resourcesVpcConfig": {
      "subnetIds": [
        "subnet-a670c2df",
        "subnet-4f8c5004"
      ]
    },
    "roleArn": "arn:aws:iam::<your-account-id>:role/AWSServiceRoleForAmazonEKS-CAC1G1VH3ZKZ",
    "clusterName": "test"
  },
  "responseElements": {
    "cluster": {
      "clusterName": "test",
      "status": "CREATING",
      "createdAt": 1527535003.208,
      "certificateAuthority": {},
      "arn": "arn:aws:eks:<region-code>:<your-account-id>:cluster/test",
      "roleArn": "arn:aws:iam::<your-account-id>:role/AWSServiceRoleForAmazonEKS-CAC1G1VH3ZKZ",
      "version": "1.10",
      "resourcesVpcConfig": {
        "securityGroupIds": [],
        "vpcId": "vpc-21277358",
        "subnetIds": [
          "subnet-a670c2df",
          "subnet-4f8c5004"
        ]
      }
    }
  },
  "requestID": "a7a0735d-62ab-11e8-9f79-81ce5b2b7d37",
  "eventID": "eab22523-174a-499c-9dd6-91e7be3ff8e3",
  "readOnly": false,
  "eventType": "AwsApiCall",
  "recipientAccountId": "<your-account-id>"
}
```


## Cloudtrail log pour l'action _DeleteInstanceProfile_ faite par _AWSServiceRoleForAmazonEKSNodegroup_ noté dans le _sessionContext_

```json
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "AROA3WHGPEZ7SJ2CW55C5:EKS",
        "arn": "arn:aws:sts::<your-account-id>:assumed-role/AWSServiceRoleForAmazonEKSNodegroup/EKS",
        "accountId": "<your-account-id>",
        "accessKeyId": "AKIAIOSFODNN7EXAMPLE",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "AROA3WHGPEZ7SJ2CW55C5",
                "arn": "arn:aws:iam::<your-account-id>:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup",
                "accountId": "<your-account-id>",
                "userName": "AWSServiceRoleForAmazonEKSNodegroup"
            },
            "webIdFederationData": {},
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2020-02-26T00:56:33Z"
            }
        },
        "invokedBy": "eks-nodegroup.amazonaws.com"
    },
    "eventTime": "2020-02-26T00:56:34Z",
    "eventSource": "iam.amazonaws.com",
    "eventName": "DeleteInstanceProfile",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "eks-nodegroup.amazonaws.com",
    "userAgent": "eks-nodegroup.amazonaws.com",
    "requestParameters": {
        "instanceProfileName": "eks-11111111-2222-3333-4444-abcdef123456"
    },
    "responseElements": null,
    "requestID": "11111111-2222-3333-4444-abcdef123456",
    "eventID": "11111111-2222-3333-4444-abcdef123456",
    "eventType": "AwsApiCall",
    "recipientAccountId": "<your-account-id>"
}
```

**Comment by GodZer** [comment]
Tous les champs n'apparaissent pas forcément dans les logs : 
 - l'attribut _uid_ dans le champ "user"
 - le champ "objectRef"
 - le champ "sourceIPs"
 
Il faut donc soit : 
- Pondérer ces champs en fonction de leur apparition
- Ne pas les pondérer du tout

**Comment by GodZer** [comment]
# Evaluation des champs de logs

## En n'incluant pas les champs variables
Description des champs et évaluation sur 10 : 
 - "kind" : 
   - Description : Valeur statique imposée par Kubernetes. Toujours sur "Event"
   - Évaluation : 0/10 - 1/10
 - "apiVersion" : 
   - Description : Version de l'API de Kubernetes utilisée. Toujours "audit.k8s.io/v1"
   - Évaluation : 0/10 - 1/10
 - "level" : 
   - Description : Valeur statique imposée par Kubernetes. Toujours "Metadata" ou "Request"
   - Évaluation
 - "auditID" : 
   - Description : 
   - Évaluation
 - "stage" : 
   - Description : 
   - Évaluation
 - "requestURI" : 
   - Description : 
   - Évaluation
 - "verb" : 
   - Description : 
   - Évaluation
 - "user" : 
   - Description : 
   - Évaluation
 - "userAgent" : 
   - Description : 
   - Évaluation
 - "responseStatus" : 
   - Description : 
   - Évaluation
 - "requestReceivedTimestamp" : 
   - Description : 
   - Évaluation
 - "stageTimestamp" : 
   - Description : 
   - Évaluation
 - "annotations" : 
   - Description : 
   - Évaluation



## En incluant les champs variables

Explication d'analyse de logs kubernetes : 
[https://kubernetes.io/docs/tasks/debug-application-cluster/audit/](url)
[https://www.datadoghq.com/blog/monitor-kubernetes-audit-logs/](url)
[https://aws-labs.com/kubernetes-audit-logging-introduction/](url)

**Comment by Shiroy** [comment]
`objectRef` **doit** être pris en compte. Il contient tous les attributs qui permettent d'identifier les éléments impacté par la requête. On y retrouve notamment:
- le nom
- le namespace
- le type d'objet

Ça va permettre d'être plus fin sur les différents coefficients à attribuer. À l'inverse, `objectURI` contient beaucoup de bruit comme les query string ou le hash Key (voir la norme de l'ietf sur les uri pour plus de détails). Cela complique l'analyse de la chaîne de caractères.

Concernant l'absence d'objectRef dans certains cas, il faut décider quoi faire. Ignorer le trail ? Remplacer par une string du type `"<missing>"` ?

**Comment by GodZer** [comment]
# Récapitulatif des paramètres pertinents sélectionnés le 10/01/2022

- `verb`
- `user`
   - `username` : Paramètre très important car ce sera aussi notre paramètre de partitionnement
   - `groups` : Permet de prévenir l'usurpation de groupes
- `userAgent`
- `annotations`
   - `authorization.k8s.in/decision` : Nous avons décidé de n'entraîner, dans un premier temps, le modèle qu'avec la valeur **allow**
- `sourceIPs` : En reflexion pour l'abandonner ou nom
- `objectRef`
  - `resource`
  - `subresource`
  - `name`
  - `namespace`

**Comment by FnyMrc** [comment]
# Poids attribués aux différents paramètres retenus

- `verb` : **3**
- `user`
   - `username` : **4**
   - `groups` : **4**
- `userAgent` : **2**
- `annotations`
   - `authorization.k8s.in/decision` : **2**
- `sourceIPs` : **1**
- `objectRef`
  - `resource` : **2**
  - `subresource` : **2**
  - `name` : **2**
  - `namespace` : **2**
- `impersonatedUser` : **2**
