### ISSUE TITLE
Déterminer le fonctionnement du couple Object2vec et RCF

### ISSUE THREAD

**Issue by FnyMrc** [GodZer/PFE-ARGOS#17]
Comprendre les liaisons des entrées sorties de chaque modèle de machine learning utilisé

**Comment by seb-jul** [comment]
Deux types sont supportés pour la donnée d'entrée d'**Object2Vec**, il va falloir pré-processer:
-  en type _token_, représenté par `integer-id` e.g.: `[10]`
- ou en type  _sequences of tokens_, représenté par `integer-ids` e.g.: `[10, 20, 30]`

De plus, il y a un input `label` qui est défini par un score de similarité, lui-même définissable par l'utilisateur #7 :
- score discret en définissant les paires d'objets comme similaires (1) ou différents (0) ; 
- **score continu** en définissant pour chaque paire d'objets un score de similarité _s_ ∈  ℝ
 
Sachant qu'on a deux _inputs channels_ en entrée, voici un exemple de ce que l'on pourrait avoir en entrée:

```sh
{"label": 0, "in0": [6, 17, 606, 19, 53, 67, 52, 12, 5, 10, 15, 10178, 7, 33, 652, 80, 15, 69, 821, 4], "in1": [16, 21, 13, 45, 14, 9, 80, 59, 164, 4]}
{"label": 1, "in0": [22, 1016, 32, 13, 25, 11, 5, 64, 573, 45, 5, 80, 15, 67, 21, 7, 9, 107, 4], "in1": [22, 32, 13, 25, 1016, 573, 3252, 4]}
{"label": 1, "in0": [774, 14, 21, 206], "in1": [21, 366, 125]}
```

Où `in0` et `in1` sont les inputs de l'encodeur0 et l'encodeur1 et où `label` est le score de similarité

**Comment by seb-jul** [comment]
Après entraînement, Object2Vec permet notamment de prédire le `label` discret ou continu entre deux nouvelles paires d'objets en entrée.

**Comment by seb-jul** [comment]
**Random Cut Forest** devrait pouvoir récupérer en input le vecteur d'output d'**Object2Vec** et fournir en output un anomaly score

**Comment by Shiroy** [comment]
Comment allez-vous transformer les strings en integers  ?
