### ISSUE TITLE
Déterminer des resources bibliographiques sur l'utilisation de batch job

### ISSUE THREAD

**Issue by FnyMrc** [GodZer/PFE-ARGOS#20]

**Comment by claire-th** [comment]
### Documentations : 

#### Vidéo par AWS :
##### AWS Batch (3min)
https://www.youtube.com/watch?v=T4aAWrGHmxQ
 ##### AWS Sagemaker Batch Transform Explication utilisation + exemple  (15min)
https://www.youtube.com/watch?v=Z9FtrRq0rc0

#### Lecture :
##### Batch 
- https://docs.aws.amazon.com/fr_fr/batch/latest/userguide/what-is-batch.html
- https://docs.aws.amazon.com/fr_fr/batch/index.html

##### Sagemaker Batch Transform
- https://docs.aws.amazon.com/fr_fr/sagemaker/latest/dg/batch-transform.html
- https://sagemaker-examples.readthedocs.io/en/latest/sagemaker_batch_transform/introduction_to_batch_transform/batch_transform_pca_dbscan_movie_clusters.html

### Résumé : 
#### Batch  :
- Alloue automatiquement les ressources de calcul et optimise la répartition de la charge de travail en fonction de la quantité et du volume des charges de travail.

#### Opération utilisant Sagemaker batch transform job : 
- Suppression du bruit/biais qui rend l'entrainement/inférence moins efficace.
- Obtention des inférences malgré une quantité volumineuse de données.
- Exécution d'un inférence sans point de terminaison persistant.
- Association des enregistrements d'entrée avec les inférences pour l'interprétation des résultats.

**Comment by Shiroy** [comment]
**/!\ Attention** : AWS Batch et AWS SageMaker Batch Transform n'ont rien à voir
