### ISSUE TITLE
Déterminer les Hyperparamètres utiles pour l'entrainement de RCF

### ISSUE THREAD

**Issue by FnyMrc** [GodZer/PFE-ARGOS#21]

**Comment by Rayan-OK** [comment]
Listes des Hyperparamètres : https://docs.aws.amazon.com/sagemaker/latest/dg/rcf_hyperparameters.html

**Comment by Rayan-OK** [comment]
### Hyperparamètres : 

_***hyperparamètres obligatoires à préciser***_

* **_feature_dim_** (min: 1, max: 10000) : nombre de features dans le data set -> lié à #14.
Nous pouvons utiliser **Random Cut Forest estimator** pour que le calcul se fasse automatiquement.

* _eval_metrics_ (`accuracy `et/ou `precision_recall_fscore `) : indicateurs utilisés pour évaluer notre modèle.
_TP = True Positive, TN = True Negative, FP = False Positive, FN = False Negative, TOTAL = TP + TN + FP + FN._
**accuracy** : nombre de prédictions correctes sur le nombre de prédiction total. Donc : 
(TP + TN)  / (TOTAL)
**precision** : quelle proportion de prédiction positive est finalement correct ?
TP/TP+FP
Dans notre cas, si nous souhaitons réduire la quantité de FP notre **precision doit se rapprocher de 1**.

 
* _num_samples_per_tree_ : 
* _num_trees_ :
