### ISSUE TITLE
Definir la fonction de similarité

### ISSUE THREAD

**Issue by Shiroy** [GodZer/PFE-ARGOS#7]
Soit deux event Kubernetes. Définir une fonction donnant un score de similarité compris entre 0 et 1. Cette fonction sera utilisée pour construire le training data set d'Object2Vec.

**Comment by FnyMrc** [comment]
Nous avons déterminé deux bloquers,
1) Définir les paramètres pertinents d'un évênement
2) Définir la fonction de similarité à utiliser pour les chaines de caaractères

Il existe 3 algorithme de similarité de chaine de caractères :
 - La distance de Hamming
- La distance de Levenstein
- La distance de Jaro-winkler

**Comment by jurix99** [comment]
#### Voici l'une des premières version de l'algorithme de smilirarités:

<img src="https://render.githubusercontent.com/render/math?math=I = nombre\_de\_trails">
</br>
<img src="https://render.githubusercontent.com/render/math?math=\omega = list\_des\_poids">
</br>
<img src="https://render.githubusercontent.com/render/math?math=trail = list\_des\_trails">
</br>
</br>
<img src="https://render.githubusercontent.com/render/math?math=For\ a\ in (0,I):">
</br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="https://render.githubusercontent.com/render/math?math=For\ b\ in (a,I):">
</br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="https://render.githubusercontent.com/render/math?math=S[a,b] = \frac{\sum_{j=0}^{I}simil(trail[a,j],trail[b,j])\times \omega[j]}{\sum_{j=0}^{I}w[j]}">
</br>
<img src="https://render.githubusercontent.com/render/math?math=return\ S">

**Comment by jurix99** [comment]
Voici la première version de l'algorithme de similarité testée en python:
(Algo de Jaro Winkler pour la similarité de string)

```py
list_parameters = []
w = [] # Poids des paramètres
nombre_trails = len(trails)
nombre_parametres = len(list_parameters)

def matrice_similarités(trails,nombre_trails,nombre_parametres,w):
  simil = [ [0]*nombre_trails for _ in range(nombre_trails) ] # Définition d'une matrice de zeros de dimension nombre_trails*nombre_trails
  for a in range(0,nombre_trails):
    for b in range(a,nombre_trails):
      tmp = 0
      for j in range(0,nombre_parametres): #Pour chaque élément des trails
        tmp += w[j] * jaro.jaro_winkler_metric(trails[a][j],trails[b][j]) # On applique l'algorithme de jaro winkler entre les logs 2 à 2 en multipliant par le poids du paramètre
      simil[a][b] = tmp/np.sum(w) # On applique une moyenne des similarités

  return simil # Matrice triangulaire supérieure
```
