### ISSUE TITLE
Fonction lambda d'ingestion

### ISSUE THREAD

**Issue by Shiroy** [GodZer/PFE-ARGOS#8]
Développer une fonction lambda permettant:
- [ ] #17 
- [ ] #16 
- remonter les anomalies à SecurityHub

**Comment by seb-jul** [comment]
Fonction lambda "de transit" suite à une évaluation

**Comment by FnyMrc** [comment]
doit-on transformer les données avant de les envoyer à Kinesis?
Quel format IT utiliser? (parquet, csv, json, xml?)
